version: "3.3"

services:
  localstack:
    container_name: sampler_localstack
    image: atlassianlabs/localstack
    ports:
      - "4569:4569"
      - "4572:4572"
      - "4575:4575"
    environment:
      - SERVICES=kinesis,dynamodb,s3
      - DEFAULT_REGION=ap-northeast-1
      - DOCKER_HOST=unix:///var/run/docker.sock
