version: "3.3"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=ap-northeast-1
      - DOCKER_HOST=unix:///var/run/docker.sock
