---
AWSTemplateFormatVersion: 2010-09-09
Description: Sempler Serverless Application Model
Transform: AWS::Serverless-2016-10-31

Resources:
  PutAttendanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: attendance
      CodeUri: src/handlers/attendance
      Handler: index.handler
      Runtime: python3.6
      Timeout: 10
      MemorySize: 128
      Role: !ImportValue sampler-iam-PutAttendanceRoleArn
      Environment:
        Variables:
          USER_TABLE_NAME: !ImportValue sampler-dynamodb-UserTableName
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: /attendance/{userId}
            Method: put

  SummaryUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: summary_users
      CodeUri: src/handlers/summary_users
      Handler: index.handler
      Runtime: python3.6
      Timeout: 10
      MemorySize: 128
      Role: !ImportValue sampler-iam-SummaryUsersRoleArn
      Environment:
        Variables:
          USER_TABLE_NAME: !ImportValue sampler-dynamodb-UserTableName
          ATTENDANCE_DATA_BUCKET_NAME: !ImportValue sampler-s3-AttendanceDataBucketName
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 * * * ? *)

  ContributeAttendancesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub contribute_attendances
      CodeUri: src/handlers/contribute_attendances
      Handler: index.handler
      Runtime: python3.6
      Timeout: 10
      MemorySize: 128
      Role: !ImportValue sampler-iam-ContributeAttendancesRoleArn
      Environment:
        Variables:
          ATTENDANCE_DATA_BUCKET_NAME: !ImportValue sampler-s3-AttendanceDataBucketName
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 * * * ? *)
