---
AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB Stack

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: UserId
          AttributeType: S
        -
          AttributeName: Attendance
          AttributeType: S
        -
          AttributeName: Place
          AttributeType: S
      KeySchema:
        -
          AttributeName: UserId
          KeyType: HASH
        -
          AttributeName: Attendance
          KeyType: RANGE
      GlobalSecondaryIndexes:
        -
          IndexName: GSI
          KeySchema:
            -
              AttributeName: Place
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  UserTableWriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 15
      MinCapacity: 5
      ResourceId: !Join
        - /
        - - table
          - !Ref UserTable
      RoleARN: !GetAtt UserTableScalingRole.Arn
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb

  UserTableScalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sampler-user-table-scaling-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        -
          PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:UpdateTable
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:SetAlarmState
                  - cloudwatch:DeleteAlarms
                Resource: "*"

  UserTableWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: sampler-user-table-write-auto-scaling-policy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref UserTableWriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 50.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization

Outputs:
  UserTableName:
    Value: !Ref UserTable
    Export:
      Name: !Sub ${AWS::StackName}-UserTableName
